# This is a basic workflow to help you get started with Actions

name: Create PR for publishing to braydenbabbitt.com

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-pr-for-braydenbabbitt:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            web-build:
              - 'build/web/**'
        
      - name: Create pull request if build has changed
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        if: steps.filter.outputs.web-build == 'true'
        env:
          API_TOKEN_GITHUB: ${{ secrets.CREATE_PR_FOR_BRAYDENBABBITT }}
        with: 
          source_folder: 'build/web/**'
          destination_repo: 'braydenbabbitt/braydenbabbitt.com'
          destination_folder: 'docs/apps/timer'
          destination_base_branch: 'master'
          destination_head_branch: 'countdown-timer-deployment'
          user_email: 'brayden@babbitts.net'
          user_name: 'braydenbabbitt'
